# Step 1 :Import Libraries

In [81]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Step 2 :Import CSV File

In [82]:
df = pd.read_csv("Patient_with_abnormal_bloodpressure.csv")
df.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0

# Step 3 : number of columns & datatype

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient_Number                 2000 non-null   int64
 1   Blood_Pressure_Abnormality     2000 non-null   int64
 2   Level_of_Hemoglobin            2000 non-null   float64
 3   Genetic_Pedigree_Coefficient   1908 non-null   float64
 4   Age                            2000 non-null   int64
 5   BMI                            2000 non-null   int64
 6   Sex                            2000 non-null   int64
 7   Pregnancy                      442 non-null    float64
 8   Smoking                        2000 non-null   int64
 9   Physical_activity              2000 non-null   int64
 10  salt_content_in_the_diet       2000 non-null   int64
 11  alcohol_consumption_per_day    1758 non-null   float64
 12  Level_of_Stress                2000 non-null   int64
 13  Chronic_kidney_disease         2000 non-null   int64
 14  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(4), int64(11)
memory usage: 234.5 KB

In [84]:
df.shape

(2000, 15)

# Step 4 : Summary of numerical columns

In [85]:
df.describe()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,1908.000000,2000.000000,2000.000000,2000.000000,442.000000,2000.000000,2000.000000,2000.000000,1758.000000,2000.000000,2000.0000,2000.000000
mean,1000.500000,0.493500,11.710035,0.494817,46.558500,30.081500,0.496000,0.450226,0.509500,25254.424500,24926.097000,251.008532,2.012500,0.5050,0.443500
std,577.494589,0.500083,2.186701,0.291736,17.107832,11.761208,0.500109,0.498080,0.500035,14015.439623,14211.692586,143.651884,0.823822,0.5001,0.496922
min,1.000000,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,500.750000,0.000000,10.147500,0.240000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,126.250000,1.000000,0.0000,0.000000
50%,1000.500000,0.000000,11.330000,0.490000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,250.000000,2.000000,1.0000,0.000000
75%,1500.250000,1.000000,12.945000,0.740000,62.000000,40.000000,1.000000,1.000000,1.000000,37382.250000,36839.750000,377.750000,3.000000,1.0000,1.000000
max,2000.000000,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

# Step 5 : Remove Duplicate rows

In [86]:
df.drop_duplicates(inplace=True)

# Step 6 : Check Missing (Null) Values

In [87]:
df.isnull().sum()[df.isnull().sum()>0]

Genetic_Pedigree_Coefficient      92
Pregnancy                       1558
alcohol_consumption_per_day      242
dtype: int64

# Step 7 : Check Objects Columns

In [88]:
df.select_dtypes(include="object").columns

Index([], dtype='str')

# Step 8 : Check Particular Column Values

In [89]:
df.Genetic_Pedigree_Coefficient.unique()
# df.Pregnancy.unique()
# df.alcohol_consumption_per_day.unique()

array([0.9 , 0.23, 0.91, 0.43, 0.83, 0.54, 0.75, 0.41, 0.68, 0.61, 0.13,
       0.1 , 0.45, 0.76, 0.06, 0.09, 0.17, 0.98, 0.57,  nan, 0.69, 0.87,
       0.74, 0.95, 0.28, 0.37, 0.93, 0.36, 0.07, 0.78, 0.2 , 0.47, 0.32,
       0.24, 0.99, 0.39, 0.01, 0.04, 0.81, 0.27, 0.3 , 0.25, 0.77, 0.49,
       0.03, 0.35, 0.7 , 0.97, 0.44, 0.63, 0.59, 0.8 , 0.96, 0.26, 0.89,
       0.82, 0.12, 0.4 , 0.33, 0.58, 0.73, 0.67, 0.38, 0.71, 0.94, 0.11,
       0.62, 0.14, 0.48, 0.84, 0.02, 0.46, 0.  , 0.19, 0.42, 0.52, 0.88,
       0.18, 0.15, 0.92, 0.31, 0.29, 0.16, 0.85, 0.55, 0.72, 0.56, 0.34,
       0.53, 0.6 , 0.08, 0.64, 0.66, 0.51, 0.5 , 0.22, 0.86, 0.21, 0.79,
       0.05, 1.  , 0.65])

# Step 9:  Handle Missing Values

In [90]:
# df['alcohol_consumption_per_day'].fillna(df['alcohol_consumption_per_day'].median(),inplace=True)
# df['Genetic_Pedigree_Coefficient'].fillna(0,inplace=True)
# df['Pregnancy'].fillna(df['Pregnancy'].median(),inplace=True)

In [91]:
# Fill missing values with median
df['alcohol_consumption_per_day'] = df['alcohol_consumption_per_day'].fillna(
    df['alcohol_consumption_per_day'].median()
)

# Fill missing values with 0
df['Genetic_Pedigree_Coefficient'] = df['Genetic_Pedigree_Coefficient'].fillna(0)

# Fill missing values with median
df['Pregnancy'] = df['Pregnancy'].fillna(
    df['Pregnancy'].median()
)

In [92]:
df.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,250.0,2,1,1
1,2,0,9.75,0.23,54,33,1,0.0,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,0.0,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,0.0,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,0.0,0,15619,49644,397.0,2,0,0

# Drop Column Blood_Pressure_Abnormality

In [93]:
# df = df.drop(['Blood_Pressure_Abnormality'],axis=1)

# Step 10 : Sampling

In [94]:
import sklearn
from sklearn.model_selection import train_test_split

In [95]:
train_df, test_df = train_test_split(df,test_size=.2,random_state=123)

In [96]:
train_df_x = train_df_x.fillna(0)
test_df_x = test_df_x.fillna(0)

In [97]:
df0=train_df[train_df.Blood_Pressure_Abnormality==1]
train_df=pd.concat([train_df,df0])

In [98]:
train_df.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1264,1265,1,15.40,0.80,31,47,1,0.0,1,15614,44371,495.0,2,0,1
722,723,0,13.66,0.30,47,30,1,0.0,1,2349,15402,194.0,3,0,0
210,211,1,9.97,0.90,63,20,0,0.0,0,6701,16318,204.0,2,0,0
252,253,1,14.36,0.35,50,26,0,0.0,1,10929,31854,224.0,1,0,1
297,298,0,13.19,0.47,26,24,0,0.0,0,36311,21035,55.0,3,0,1

In [99]:
train_df_x = train_df.drop(train_df.columns[1],axis=1)
train_df_y = train_df.iloc[:,1]

test_df_x = test_df.drop(test_df.columns[1],axis=1)
test_df_y = test_df.iloc[:,1]

# Step 11 : model build

In [101]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(train_df_x,train_df_y)
pred_test = model.predict(test_df_x)
from sklearn.metrics import *
tab=confusion_matrix(test_df_y,pred_test)
print(tab)
print(classification_report(test_df_y,pred_test))

[[  0 191]
 [  0 209]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       191
           1       0.52      1.00      0.69       209

    accuracy                           0.52       400
   macro avg       0.26      0.50      0.34       400
weighted avg       0.27      0.52      0.36       400

In [79]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(train_df_x,train_df_y)
pred_test = model.predict(test_df_x)
from sklearn.metrics import *
tab=confusion_matrix(test_df_y,pred_test)
print(tab)
print(classification_report(test_df_y,pred_test))

[[165  26]
 [ 36 173]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       191
           1       0.87      0.83      0.85       209

    accuracy                           0.84       400
   macro avg       0.85      0.85      0.84       400
weighted avg       0.85      0.84      0.85       400

In [102]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(train_df_x,train_df_y)
pred_test = model.predict(test_df_x)
from sklearn.metrics import *
tab=confusion_matrix(test_df_y,pred_test)
print(tab)
print(classification_report(test_df_y,pred_test))

[[161  30]
 [ 15 194]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.88       191
           1       0.87      0.93      0.90       209

    accuracy                           0.89       400
   macro avg       0.89      0.89      0.89       400
weighted avg       0.89      0.89      0.89       400